set -g default-terminal "screen-256color"
set -s escape-time 0
set -g base-index 1
set -g renumber-window on
set -g mouse on
set -g focus-events on

# Place status bar at top and add an empty space below it
set -g status-position top
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[1]' ''
set -g status 2

# Change backslash
unbind %
bind \\ split-window -h

# Change vertical split to -
unbind '"'
bind - split-window -v

unbind C-b
set-option -g prefix C-,

# Change config reload to r
unbind r
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"

# Change visual mode to v
unbind [
unbind v
bind v copy-mode

# Enable vim motions in copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"

# Simpler window navigation
bind -n C-[ previous-window
bind -n C-] next-window

# Don't exit copy mode on mouse selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Install plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux"

# Catppuccin configuration

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "#{@thm_bg}"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text "#[bg=default] #W"
set -g @catppuccin_window_current_text "#[bg=default] #W"

# Cattpuccing initialization

run "$XDG_CONFIG_HOME/tmux/plugins/tmux/catppuccin.tmux"

# Status bar configuration

set -g window-status-separator ""
set -g status-left ""
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold]TMUX "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY   ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""
set -g status-right-length 0
set -g status-right "#[fg=#{@thm_fg} bold]#S"

# TPM initialization (keep it at the bottom of this file)
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
